import "../styles/globals.css";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import SubMenu from "./components/SubMenu/SubMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <SubMenu current="Home" active="Shop" />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
