import "../styles/globals.css";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import SubMenu from "./components/SubMenu/SubMenu";
import { ProductProvider } from "./context/ProductContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProductProvider>
          <Navbar />
          <SubMenu current="Home" active="Shop" />
          {children}
          <Footer />
        </ProductProvider>
      </body>
    </html>
  );
}
